name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Checkout Azure DevOps repo
        uses: actions/checkout@v3
        with:
          repository: "https://willianoliveir1@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff"
          token: ${{ secrets.AZURE_DEVOPS_PAT }}
          path: azure-repo

      - name: Copy files
        run: |
          cp -r ./ azure-repo/

      - name: Commit and push to Azure DevOps
        run: |
          cd azure-repo
          git config --global user.email "flaviomateus@id.uff.br" 
          git config --global user.name "FlavioMateus" 
          git add .
          git commit -m "Sync from GitHub"
          git push origin main 
