name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone Azure DevOps repo
        run: |
          git clone https://${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff azure-repo

      - name: Copy files from GitHub checkout to Azure DevOps repo
        run: |
          cp -r $GITHUB_WORKSPACE/* azure-repo/

      - name: Commit and push to Azure DevOps
        run: |
          cd azure-repo
          git config --global user.email "flaviomateus@id.uff.br"
          git config --global user.name "FlavioMateus"
          git add .
          git commit -m "Sync from GitHub" || echo "Nothing to commit"
          git push origin main
