name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone Azure DevOps repo
        run: |
          git clone https://$AZURE_DEVOPS_PAT@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff azure-repo
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Sync files to Azure DevOps repo
        run: |
          rsync -av --exclude='.git/' ./ azure-repo/

      - name: Debug token
        run: |
          echo "Token starts with: ${AZURE_DEVOPS_PAT:0:4}********"
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      - name: Commit and push to Azure DevOps
        run: |
          cd azure-repo
          git remote set-url origin https://$AZURE_DEVOPS_PAT@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff
          git config user.email "flaviomateuspf@hotmail.com.br"
          git config user.name "Flavio Mateus"
          git add .
          git commit -m "Sync from GitHub" || echo "Nothing to commit"
          git push https://$AZURE_DEVOPS_PAT@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff main
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
