name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Clone Azure DevOps repo
        run: |
          git clone https://$AZURE_DEVOPS_PAT@dev.azure.com/willianoliveir1/uff-es2-balcaouff/_git/uff-es2-balcaouff azure-repo

      - name: Copy files
        run: |
          cp -r ./ azure-repo/

      - name: Commit and push to Azure DevOps
        run: |
          cd azure-repo
          git config user.email "flaviomateus@id.uff.br"
          git config user.name "FlavioMateus"
          git add .
          git commit -m "Sync from GitHub" || echo "Nothing to commit"
          git push origin main
    env:
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
